name: Build and Release

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4  # Updated to v4
        with:
          dotnet-version: '9.x'  

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./TicTacToeMinimax/WinFormsApp1

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./TicTacToeMinimax/WinFormsApp1

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ./TicTacToeMinimax/WinFormsApp1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: TicTacToeMinimax
          path: ./TicTacToeMinimax/WinFormsApp1/publish

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Create and push tag
        run: |
          $TAG_NAME = "Icncl"
          git tag $TAG_NAME
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: TicTacToeMinimax

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v4  # Updated to v4
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
