name: Build and Release

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Update to your .NET version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./TicTacToeMinimax

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./TicTacToeMinimax

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ./TicTacToeMinimax

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TicTacToeMinimax
          path: ./publish

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: TicTacToeMinimax

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
